os: linux
dist: xenial
language: python
python:
  - '3.8'
cache: pip
install:
  - cd /home/travis/build/elcolumbio/cctable/
  - pip install -r requirements.txt
  - pip install .

script:
  - flake8 ./cctable/
  - flake8 ./tests
  - pytest